/* tslint:disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
export const environment = {
  "production": true,
  "sitecoreApiHost": "http://ionic4.dev.local",
  "sitecoreApiKey": "{D2999BDD-B2AD-4C13-870E-352B8546AA69}",
  "jssAppName": "ionic4",
  "sitecoreLayoutServiceConfig": "jss",
  "defaultLanguage": "en",
  "defaultServerRoute": "/",
  "graphQLEndpointPath": "/api/ionic4",
  "graphQLEndpoint": "http://ionic4.dev.local/api/ionic4?sc_apikey={D2999BDD-B2AD-4C13-870E-352B8546AA69}"
};
